# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookingFood' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookingFood
  pod "Kingfisher"
  pod 'ProgressHUD'
  pod "IQKeyboardManagerSwift"		
end
